autopkg/bochoven-recipes

- Opera/Opera.munki.recipe
Not sure how you feel about this change... Opera has seen a lot of small build number changes lately and this PR changes the version handling for Munki: `27.0.1689.69` instead of `27.0`.
> Use CFBundleVersion instead of CFBundleShortVersionString

- Opera/Opera.download.recipe
The double dash in front of `--display` was hindering automatic parsing of the Opera download recipe using Python's plistlib.
> Change inline comment to separate key/value pair

- Opera/Opera.download.recipe
CodeSignatureVerifier requirement string changed to identifier "com.operasoftware.Opera" and certificate leaf = H"cdf1c39967986616b6cd64c6bd04833a9cb7450d"
> CodeSignatureVerifier requirement string changed

- JASP/JASP.munki.recipe
It appears that JASP 0.9+ has been built for 10.12+. There is a special build for older versions available, but I guess the new default will require 10.12.
> JASP: set munki minimum os to 10.12

- JASP/JASP.download.recipe
Looks like the URL got changed to HTTP
> Fix JASP download URL

- JASP/JASP.download.recipe
Context: The [CodeSignatureVerifier](https://github.com/autopkg/autopkg/wiki/Using-CodeSignatureVerification) processor ensures that the downloaded applications/packages are signed by the expected developer certificate. Although this is not a guarantee that the payload is trouble-free, it's a good indicator that the file you downloaded is the one you intended to download.
> Add CodeSignatureVerifier processor

- Opera/Opera.munki.recipe
Reverts change 48ea8f0ba17eb5e17d0662e244a332cbc01f1339 made to fix https://github.com/autopkg/bochoven-recipes/issues/11, because the bundle permissions have been fixed by the Opera developers.
```
ls -la /Volumes/Opera/Opera.app/Contents/Versions/63.0.3368.53/Opera\ Framework.framework/
total 24
drwxr-xr-x  6 dfnq  185223974   204B Aug 26 13:03 ./
drwxr-xr-x  8 dfnq  185223974   272B Aug 26 22:32 ../
lrwxr-xr-x  1 dfnq  185223974    24B Aug 28 22:21 Helpers@ -> Versions/Current/Helpers
lrwxr-xr-x  1 dfnq  185223974    32B Aug 28 22:21 Opera Framework@ -> Versions/Current/Opera Framework
lrwxr-xr-x  1 dfnq  185223974    26B Aug 28 22:21 Resources@ -> Versions/Current/Resources
drwxr-xr-x  4 dfnq  185223974   136B Aug 26 13:03 Versions/
```
> Remove Opera postinstall script

- Opera/OperaUpdateInfoProvider.py
This PR updates OperaUpdateInfoProvider to use the new [URLGetter superclass](https://github.com/autopkg/autopkg/wiki/Downloading-from-the-Internet-in-Custom-Processors), which should ease the transition to Python 3 and AutoPkg 2.
Verbose run log:
https://gist.github.com/homebysix/5d94da86a52d2d765e993b66da9d61d6
> Use URLGetter superclass for OperaUpdateInfoProvider

- Orchard & Grove/NoMADLogin-AD.munki.recipe
I updated my autopkg to 1.4.1 today and updated this recipe as well and got the following error:
Error: Error in local.munki.NoMADLogin-AD: Processor: MunkiImporter: Error: creating pkginfo for %found_filename% failed: Traceback (most recent call last):
File "/usr/local/munki/makepkginfo", line 142, in <module>
main()
File "/usr/local/munki/makepkginfo", line 123, in main
item = pkginfo['name']
KeyError: 'name'
I found that the %found_filename% was probably a leftover from the old ZIP retrieval method that was retired, and was not allowing the recipe to proceed as the value would be blank. Since the change was to a direct .pkg download, we can just use %pathname%. Tested on AutoPkg 1.4.1 - no issues found. Did not test on the 2.0RC.
> Update variable for pkg_path in NoMADLogin-AD recipe

- JASP/JASP.download.recipe
JASP has deprecated the old thank you page, replacing it with new ones that are OS-specific.
Please note that currently, on the new page, the download link links to the Windows installer. I have already emailed JASP asking them to fix this issue.
> Updated JASP download URL

- ADF/ADF.munki.recipe
- VU-DAMS/VU_DAMS.munki.recipe
`pkg_path` is not a valid argument for [MunkiPkginfoMerger](https://github.com/autopkg/autopkg/wiki/Processor-MunkiPkginfoMerger).
> Adjust MunkiPkginfoMerger arguments

- JASP/JASP.download.recipe
The correct argument name for [CodeSignatureVerifier](https://github.com/autopkg/autopkg/wiki/Processor-CodeSignatureVerifier) is `requirement`.
> Adjust name of CodeSignatureVerifier argument

- Albert-Georg Lang/G*Power.download.recipe
- Albert-Georg Lang/G*Power.munki.recipe
1. The redirect from https://www.gpower.hhu.de to https://www.psychologie.hhu.de breaks the `%DOWNLOAD_URL%%match%` pattern.
2. The HTML is now a single line and the re_pattern was too greedy, limited `\S+`
3. While I was at it, I also integrated the short description and the team name taken from https://www.psychologie.hhu.de/arbeitsgruppen/allgemeine-psychologie-und-arbeitspsychologie/gpower
> Fix URLs, regex, description & author for G*Power

- PsychoPy/PsychoPy3.download.recipe
The last release referencing PsychoPy3 was Release 2020.2.3. They ditched the "3" and also lowercased "macOS" now.
> PsychoPy3: Fix github release regex

- PsychoPy/PsychoPy3.download.recipe
The dmg takes very long to actually start downloading from github. Maybe they are checking the dmg first, I don't know. They default `--speed-time 30` is not sufficient for this package and the download always fails with curl error 28. Override the speed-time parameter by appending does fix this problem.
> PsychoPy3: Increase curl timeout

- ADF/ADF.download.recipe
ADF is now part of the AMS package, instead of ADF being its own product. This means that SCM has updated the download URLs for 2020 and newer. I've added to the regex so you can still match both.
```
autopkg run -v ADF.download.recipe -k BASEVERSION=2021 -k AUTH_HASH="S0m3H4sH"
Processing ADF.download.recipe...
WARNING: ADF.download.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
URLTextSearcher
URLTextSearcher: Found matching text (match): ams2021.104.macintel64.openmpi
URLDownloader
URLDownloader: Storing new Last-Modified header: Tue, 14 Sep 2021 09:35:15 GMT
URLDownloader: Storing new ETag header: "a19924cf-5cbf14c92985c"
URLDownloader: Downloaded /Users/jc0b/Library/AutoPkg/Cache/com.github.bochoven.recipes.download.ADF/downloads/ams2021.104 …
```
> Updated regex for ADF renaming to AMS

- Opera/OperaUpdateInfoProvider.py
As of macOS Monterey 12.3, the version of Python 2 that shipped with macOS located at `/usr/bin/python` [has been removed](https://developer.apple.com/documentation/macos-release-notes/macos-12_3-release-notes). More context can be found in some posts from Mac admins at the beginning of 2022, aggregated [here](https://scriptingosx.com/2022/03/macos-monterey-12-3-removes-python-2-link-collection/).
Since [version 2.0.2](https://github.com/autopkg/autopkg/releases/tag/v2.0.2), AutoPkg's installer has included its own Python 3 framework, symlinked from `/usr/local/autopkg/python`. This pull request adjusts the "shebang" interpreter paths of processors to replace `/usr/bin/env python` with the AutoPkg Python 3 path.
NOTE: Because AutoPkg processors are imported as modules by AutoPkg and not …
> Update Python path in processors to reflect changes in macOS 12.3+

- JASP/JASP.download.recipe
To avoid conflicts when importing both arm and intel.
Before the change, running an arm override of the recipe and then the intel override would result in the downloaded dmgs that were imported into munki being named "JASP-0.18.0-0.18.dmg" and "JASP-0.18.0-0.18__1.dmg" with no indication of which dmg contained which architecture without referencing the munki pkginfo file.
After making this change:
Running the overridden recipe for the arm64 architecture:
autopkg run -v JASP_arm64.munki
Processing JASP_arm64.munki...
GitHubReleasesInfoProvider
GitHubReleasesInfoProvider: Matched regex 'JASP-([0-9]+(\.[0-9]+)+)-macOs-arm64\.dmg$' among asset(s): JASP-0.18.0.0-macOs-arm64.dmg, JASP-0.18.0.0-macOs-x86_64.dmg, JASP-0.18.0.0-Windows.msi, JASP-0.18.0.0-Windows.zip
GitHubReleasesInfoProvider: …
> Add ARCHITECTURE to filename

- JASP/JASP.download.recipe
~ % autopkg run -v jasp.download.recipe
Processing jasp.download.recipe...
GitHubReleasesInfoProvider
GitHubReleasesInfoProvider: Matched regex '(?i)JASP-([0-9]+(\.[0-9]+)+)-macOs-arm64.*\.dmg$' among asset(s): JASP-0.19.0.0-macOS-arm64.dmg, JASP-0.19.0.0-macOS-x86_64.dmg, JASP-0.19.0.0-Windows.msi, JASP-0.19.0.0-Windows.zip
GitHubReleasesInfoProvider: Selected asset 'JASP-0.19.0.0-macOS-arm64.dmg' from release 'Release 0.19.0'
URLDownloader
URLDownloader: Storing new Last-Modified header: Mon, 15 Jul 2024 20:36:11 GMT
URLDownloader: Storing new ETag header: "0x8DCA50DC3DE8B2F"
URLDownloader: Downloaded /Users/Shared/AutoPkg/Cache/local.download.jasp/downloads/JASP_arm64-0.19.0.dmg
EndOfCheckPhase
CodeSignatureVerifier
CodeSignatureVerifier: Mounted disk image …
> Update CodeSignature for Jasp Download

- JASP/JASP.munki.recipe
For minor updates to JASP, CFBundleVersion will update while CFBundleShortVersionString will not.  This pull request allows minor updates to import correctly into Munki.
> Remove App DmgVersioner and set MunkiImporter to use CFBundleVersion

- JASP/JASP.munki.recipe
Apologies for the additional pull request.  I should have bought this and included in in the last one.  
This change passes `%version%` from the `GitHubReleasesInfoProvider` step to `MunkiImporter` by way of `additional_makepkginfo_options`
> pass version to munkiimporter

- PsychoPy/PsychoPy2.download.recipe
- PsychoPy/PsychoPy3.download.recipe
This PR updates the PsychoPy family of recipes to support the latest release on GitHub, adds code signature verification, and deprecates the non-working PsychoPy2 recipes.
```
% autopkg run -vvq 'PsychoPy/PsychoPy3.download.recipe'
Processing PsychoPy/PsychoPy3.download.recipe...
WARNING: PsychoPy/PsychoPy3.download.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
GitHubReleasesInfoProvider
{'Input': {'asset_regex': '^StandalonePsychoPy-[\\d\\.]+-macOS-3.10\\.dmg$',
'github_repo': 'psychopy/psychopy'}}
GitHubReleasesInfoProvider: No value supplied for CURL_PATH, setting default value of: /usr/bin/curl
GitHubReleasesInfoProvider: No value supplied for GITHUB_URL, setting default value of: https://api.github.com
GitHubReleasesInfoProvider: No value …
```
> Fix PsychoPy 3 recipes and add code signature verification, deprecate PsychoPy 2 recipes

- Albert-Georg Lang/G*Power.download.recipe
This PR deprecates the non-functional G*Power recipe family, and points users to the working equivalents in the dataJAR-recipes repo.
> Deprecate GPower recipes

- WebDrive/WebDrive.download.recipe
This PR adjusts the WebDrive download method and adds code signature verification.
```
% autopkg run -vvq 'WebDrive/WebDrive.download.recipe'
Processing WebDrive/WebDrive.download.recipe...
WARNING: WebDrive/WebDrive.download.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
URLDownloader
{'Input': {'url': 'https://srtcdnstorage.blob.core.windows.net/software/nextgen/webdrive/WebDrive%20Setup.pkg'}}
URLDownloader: No value supplied for prefetch_filename, setting default value of: False
URLDownloader: No value supplied for CHECK_FILESIZE_ONLY, setting default value of: False
URLDownloader: Storing new Last-Modified header: Tue, 18 Jul 2023 18:26:06 GMT
URLDownloader: Storing new ETag header: 0x8DB87BC73D31452
URLDownloader: Downloaded …
```
> Fix WebDrive recipes and add code signature verification

- Orchard & Grove/NoMADLogin-AD.download.recipe
This PR deprecates the NoMAD Login AD recipes, since the software will be receiving no futher updates ([details](https://www.jamf.com/blog/jamf-to-archive-nomad-open-source-projects/)).
> Deprecate NoMAD Login AD recipes

- WebDrive/WebDrive.download.recipe
My previous PR introduced a minor issue: the proper name for this key should be `expected_authority_names`. This PR has the fix.
> Update expected_authorities to expected_authority_names in CodeSignatureVerifier

- Albert-Georg Lang/G*Power.pkg.recipe
- JASP/JASP.pkg.recipe
- PsychoPy/PsychoPy2.pkg.recipe
Hundreds of recipes dating from the very beginning of AutoPkg use the `options` key in the `pkg_request` argument of PkgCreator:
```xml
<key>options</key>
<string>purge_ds_store</string>
```
However, this key doesn't serve any purpose at all. The `options` key is ignored and not passed along to `pkgbuild`, regardless of its presence or contents. It appears that this has been the case since the very first public release of AutoPkg 0.1.0!
So this pull request (one of over 100) formally ends this practice and removes the unused and unneeded `options` key from all recipes in the AutoPkg org that use PkgCreator.
Thanks for considering!
_This PR was submitted using [Repo Lasso](https://github.com/homebysix/repo-lasso) v1.2.0._
> Removal of unused `options` from PkgCreator arguments
